apiVersion: v1
kind: Pod
metadata:
  name: vol-git
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
    - name: srv
      mountPath: /srv
  volumes:
  - name: srv
    gitRepo:
      repository: https://github.com/shell909090/k8s-in-progress.git
      revision: main
