apiVersion: v1
kind: Pod
metadata:
  name: vol-git
spec:
  containers:
  - name: deb
    image: debian
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
    - name: srv
      mountPath: /srv
  volumes:
  - name: srv
    gitRepo:
      repository: https://github.com/shell909090/webserver.git
      revision: master
