apiVersion: v1
kind: Pod
metadata:
  name: vol-pvc-nfs
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
      - name: srv
        mountPath: /srv
  volumes:
    - name: srv
      persistentVolumeClaim:
        claimName: nfs
