apiVersion: v1
kind: Pod
metadata:
  name: req-high
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    resources:
      requests:
        cpu: 1
        memory: 1000Mi
