apiVersion: v1
kind: Pod
metadata:
  name: deb-req-low
spec:
  containers:
  - name: deb
    image: debian
    command:
      - /bin/sleep
    args:
      - "1000000"
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
      # limits:
      #   cpu: 200m
      #   memory: 100Mi
    volumeMounts:
    - name: apt
      mountPath: /etc/apt/sources.list
      subPath: sources.list
      readOnly: true
    - name: apt
      mountPath: /etc/apt/apt.conf.d/98proxy
      subPath: 98proxy
      readOnly: true
  volumes:
  - name: apt
    configMap:
      name: apt
