apiVersion: v1
kind: Pod
metadata:
  name: req-impossible
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    resources:
      requests:
        cpu: 5
        memory: 5000Mi
