apiVersion: v1
kind: Pod
metadata:
  name: req-low
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
      # limits:
      #   cpu: 200m
      #   memory: 100Mi
