apiVersion: v1
kind: Pod
metadata:
  name: file
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
    - name: file
      mountPath: /srv/
  volumes:
  - name: file
    hostPath:
      path: /
      type: ""
