apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: debian
    command: ["sleep", "1000000"]
    volumeMounts:
    - name: apt
      mountPath: /etc/apt/sources.list
      subPath: sources.list
      readOnly: true
    - name: apt
      mountPath: /etc/apt/apt.conf.d/98proxy
      subPath: 98proxy
      readOnly: true
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
  volumes:
  - name: apt
    configMap:
      name: apt
