apiVersion: v1
kind: Pod
metadata:
  name: deb-downward
spec:
  containers:
  - name: deb
    image: debian
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
    - name: apt
      mountPath: /etc/apt/sources.list
      subPath: sources.list
      readOnly: true
    - name: apt
      mountPath: /etc/apt/apt.conf.d/98proxy
      subPath: 98proxy
      readOnly: true
    - name: downward
      mountPath: /etc/downward/
  volumes:
  - name: apt
    configMap:
      name: apt
  - name: downward
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
