apiVersion: v1
kind: Pod
metadata:
  name: downward
  labels:
    app: downward
spec:
  containers:
  - name: ubt
    image: ubuntu
    command:
      - /bin/sleep
    args:
      - "1000000"
    volumeMounts:
    - name: downward
      mountPath: /etc/downward/
    resources: {}
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
